language: python
env:
  - DJANGO_SETTINGS_MODULE=
  - DJANGO_VERSION=1.6
  - DJANGO_VERSION=1.7
  - DJANGO_VERSION=1.8
python:
  - "2.7"
  - "3.3"
  - "3.4"
# command to install dependencies
install:
  - pip install -q Django==$DJANGO_VERSION
  - pip install -q .
  - pip install -q -r requirements.txt
# command to run tests
script: nosetests tests
